# This file contains values from Cookiecutter

default_context:
  project_name: "poli-holas"
  project_description: "Saludar en m√∫ltiples idiomas"
  organization: "fraediaz"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.7
  github_name: "fraediaz"
  email: "fraediaz@icloud.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
